export type Problem = { name: string; url: string; difficulty: "Easy" | "Medium" | "Hard" };
export type TopicNode = { id: string; label: string; x: number; y: number; problems: Problem[]; prerequisites?: string[] };
export type Edge = { from: string; to: string };

const LC = (slug: string) => `https://leetcode.com/problems/${slug}/`;

export const NODES: TopicNode[] = [
  { id: "arrays", label: "Arrays & Hashing", x: 50, y: 0, problems: [
    { name: "Two Sum", url: LC("two-sum"), difficulty: "Easy" },
    { name: "Contains Duplicate", url: LC("contains-duplicate"), difficulty: "Easy" },
    { name: "Valid Anagram", url: LC("valid-anagram"), difficulty: "Easy" },
    { name: "Group Anagrams", url: LC("group-anagrams"), difficulty: "Medium" },
    { name: "Top K Frequent Elements", url: LC("top-k-frequent-elements"), difficulty: "Medium" },
    { name: "Product of Array Except Self", url: LC("product-of-array-except-self"), difficulty: "Medium" },
    { name: "Encode and Decode Strings", url: LC("encode-and-decode-strings"), difficulty: "Medium" },
    { name: "Longest Consecutive Sequence", url: LC("longest-consecutive-sequence"), difficulty: "Medium" },
    { name: "Sort Colors", url: LC("sort-colors"), difficulty: "Medium" },
    { name: "Next Permutation", url: LC("next-permutation"), difficulty: "Medium" },
  ]},
  { id: "two-pointers", label: "Two Pointers", x: 30, y: 1, prerequisites: ["arrays"], problems: [
    { name: "Valid Palindrome", url: LC("valid-palindrome"), difficulty: "Easy" },
    { name: "Two Sum II", url: LC("two-sum-ii-input-array-is-sorted"), difficulty: "Medium" },
    { name: "3Sum", url: LC("3sum"), difficulty: "Medium" },
    { name: "Container With Most Water", url: LC("container-with-most-water"), difficulty: "Medium" },
    { name: "Trapping Rain Water", url: LC("trapping-rain-water"), difficulty: "Hard" },
  ]},
  { id: "stack", label: "Stack", x: 70, y: 1, prerequisites: ["arrays"], problems: [
    { name: "Valid Parentheses", url: LC("valid-parentheses"), difficulty: "Easy" },
    { name: "Min Stack", url: LC("min-stack"), difficulty: "Medium" },
    { name: "Evaluate Reverse Polish Notation", url: LC("evaluate-reverse-polish-notation"), difficulty: "Medium" },
    { name: "Generate Parentheses", url: LC("generate-parentheses"), difficulty: "Medium" },
    { name: "Daily Temperatures", url: LC("daily-temperatures"), difficulty: "Medium" },
    { name: "Car Fleet", url: LC("car-fleet"), difficulty: "Medium" },
    { name: "Largest Rectangle in Histogram", url: LC("largest-rectangle-in-histogram"), difficulty: "Hard" },
  ]},
  { id: "binary-search", label: "Binary Search", x: 15, y: 2, prerequisites: ["two-pointers"], problems: [
    { name: "Binary Search", url: LC("binary-search"), difficulty: "Easy" },
    { name: "Search a 2D Matrix", url: LC("search-a-2d-matrix"), difficulty: "Medium" },
    { name: "Koko Eating Bananas", url: LC("koko-eating-bananas"), difficulty: "Medium" },
    { name: "Find Min in Rotated Array", url: LC("find-minimum-in-rotated-sorted-array"), difficulty: "Medium" },
    { name: "Search Rotated Sorted Array", url: LC("search-in-rotated-sorted-array"), difficulty: "Medium" },
    { name: "Time Based Key-Value Store", url: LC("time-based-key-value-store"), difficulty: "Medium" },
    { name: "Median of Two Sorted Arrays", url: LC("median-of-two-sorted-arrays"), difficulty: "Hard" },
  ]},
  { id: "sliding-window", label: "Sliding Window", x: 42, y: 2, prerequisites: ["two-pointers"], problems: [
    { name: "Best Time to Buy & Sell Stock", url: LC("best-time-to-buy-and-sell-stock"), difficulty: "Easy" },
    { name: "Longest Substring No Repeat", url: LC("longest-substring-without-repeating-characters"), difficulty: "Medium" },
    { name: "Longest Repeating Char Replace", url: LC("longest-repeating-character-replacement"), difficulty: "Medium" },
    { name: "Permutation in String", url: LC("permutation-in-string"), difficulty: "Medium" },
    { name: "Minimum Window Substring", url: LC("minimum-window-substring"), difficulty: "Hard" },
    { name: "Sliding Window Maximum", url: LC("sliding-window-maximum"), difficulty: "Hard" },
  ]},
  { id: "linked-list", label: "Linked List", x: 68, y: 2, prerequisites: ["stack"], problems: [
    { name: "Reverse Linked List", url: LC("reverse-linked-list"), difficulty: "Easy" },
    { name: "Merge Two Sorted Lists", url: LC("merge-two-sorted-lists"), difficulty: "Easy" },
    { name: "Linked List Cycle", url: LC("linked-list-cycle"), difficulty: "Easy" },
    { name: "Reorder List", url: LC("reorder-list"), difficulty: "Medium" },
    { name: "Remove Nth From End", url: LC("remove-nth-node-from-end-of-list"), difficulty: "Medium" },
    { name: "Copy List Random Pointer", url: LC("copy-list-with-random-pointer"), difficulty: "Medium" },
    { name: "Add Two Numbers", url: LC("add-two-numbers"), difficulty: "Medium" },
    { name: "LRU Cache", url: LC("lru-cache"), difficulty: "Medium" },
    { name: "Merge K Sorted Lists", url: LC("merge-k-sorted-lists"), difficulty: "Hard" },
    { name: "Reverse Nodes in K-Group", url: LC("reverse-nodes-in-k-group"), difficulty: "Hard" },
  ]},
  { id: "trees", label: "Trees", x: 42, y: 3, prerequisites: ["binary-search", "linked-list"], problems: [
    { name: "Invert Binary Tree", url: LC("invert-binary-tree"), difficulty: "Easy" },
    { name: "Max Depth of Binary Tree", url: LC("maximum-depth-of-binary-tree"), difficulty: "Easy" },
    { name: "Diameter of Binary Tree", url: LC("diameter-of-binary-tree"), difficulty: "Easy" },
    { name: "Balanced Binary Tree", url: LC("balanced-binary-tree"), difficulty: "Easy" },
    { name: "Same Tree", url: LC("same-tree"), difficulty: "Easy" },
    { name: "Subtree of Another Tree", url: LC("subtree-of-another-tree"), difficulty: "Easy" },
    { name: "Level Order Traversal", url: LC("binary-tree-level-order-traversal"), difficulty: "Medium" },
    { name: "Right Side View", url: LC("binary-tree-right-side-view"), difficulty: "Medium" },
    { name: "Count Good Nodes", url: LC("count-good-nodes-in-binary-tree"), difficulty: "Medium" },
    { name: "Validate BST", url: LC("validate-binary-search-tree"), difficulty: "Medium" },
    { name: "Kth Smallest in BST", url: LC("kth-smallest-element-in-a-bst"), difficulty: "Medium" },
    { name: "Lowest Common Ancestor", url: LC("lowest-common-ancestor-of-a-binary-search-tree"), difficulty: "Medium" },
    { name: "Construct from Pre+In", url: LC("construct-binary-tree-from-preorder-and-inorder-traversal"), difficulty: "Medium" },
    { name: "Max Path Sum", url: LC("binary-tree-maximum-path-sum"), difficulty: "Hard" },
    { name: "Serialize & Deserialize", url: LC("serialize-and-deserialize-binary-tree"), difficulty: "Hard" },
  ]},
  { id: "tries", label: "Tries", x: 20, y: 4, prerequisites: ["trees"], problems: [
    { name: "Implement Trie", url: LC("implement-trie-prefix-tree"), difficulty: "Medium" },
    { name: "Add and Search Word", url: LC("design-add-and-search-words-data-structure"), difficulty: "Medium" },
    { name: "Word Search II", url: LC("word-search-ii"), difficulty: "Hard" },
  ]},
  { id: "backtracking", label: "Backtracking", x: 58, y: 4, prerequisites: ["trees"], problems: [
    { name: "Subsets", url: LC("subsets"), difficulty: "Medium" },
    { name: "Combination Sum", url: LC("combination-sum"), difficulty: "Medium" },
    { name: "Combination Sum II", url: LC("combination-sum-ii"), difficulty: "Medium" },
    { name: "Permutations", url: LC("permutations"), difficulty: "Medium" },
    { name: "Subsets II", url: LC("subsets-ii"), difficulty: "Medium" },
    { name: "Word Search", url: LC("word-search"), difficulty: "Medium" },
    { name: "Palindrome Partitioning", url: LC("palindrome-partitioning"), difficulty: "Medium" },
    { name: "Letter Combinations", url: LC("letter-combinations-of-a-phone-number"), difficulty: "Medium" },
    { name: "N-Queens", url: LC("n-queens"), difficulty: "Hard" },
  ]},
  { id: "heap", label: "Heap / Priority Queue", x: 10, y: 5, prerequisites: ["tries"], problems: [
    { name: "Kth Largest Element Stream", url: LC("kth-largest-element-in-a-stream"), difficulty: "Easy" },
    { name: "Last Stone Weight", url: LC("last-stone-weight"), difficulty: "Easy" },
    { name: "K Closest Points", url: LC("k-closest-points-to-origin"), difficulty: "Medium" },
    { name: "Kth Largest in Array", url: LC("kth-largest-element-in-an-array"), difficulty: "Medium" },
    { name: "Task Scheduler", url: LC("task-scheduler"), difficulty: "Medium" },
    { name: "Design Twitter", url: LC("design-twitter"), difficulty: "Medium" },
    { name: "Find Median Data Stream", url: LC("find-median-from-data-stream"), difficulty: "Hard" },
  ]},
  { id: "graphs", label: "Graphs", x: 42, y: 5, prerequisites: ["backtracking", "tries"], problems: [
    { name: "Number of Islands", url: LC("number-of-islands"), difficulty: "Medium" },
    { name: "Clone Graph", url: LC("clone-graph"), difficulty: "Medium" },
    { name: "Max Area of Island", url: LC("max-area-of-island"), difficulty: "Medium" },
    { name: "Pacific Atlantic Water Flow", url: LC("pacific-atlantic-water-flow"), difficulty: "Medium" },
    { name: "Surrounded Regions", url: LC("surrounded-regions"), difficulty: "Medium" },
    { name: "Rotting Oranges", url: LC("rotting-oranges"), difficulty: "Medium" },
    { name: "Course Schedule", url: LC("course-schedule"), difficulty: "Medium" },
    { name: "Course Schedule II", url: LC("course-schedule-ii"), difficulty: "Medium" },
    { name: "Graph Valid Tree", url: LC("graph-valid-tree"), difficulty: "Medium" },
    { name: "Number of Connected Components", url: LC("number-of-connected-components-in-an-undirected-graph"), difficulty: "Medium" },
    { name: "Word Ladder", url: LC("word-ladder"), difficulty: "Hard" },
  ]},
  { id: "dp1", label: "1-D DP", x: 72, y: 5, prerequisites: ["backtracking"], problems: [
    { name: "Climbing Stairs", url: LC("climbing-stairs"), difficulty: "Easy" },
    { name: "Min Cost Climbing Stairs", url: LC("min-cost-climbing-stairs"), difficulty: "Easy" },
    { name: "House Robber", url: LC("house-robber"), difficulty: "Medium" },
    { name: "House Robber II", url: LC("house-robber-ii"), difficulty: "Medium" },
    { name: "Longest Palindromic Substring", url: LC("longest-palindromic-substring"), difficulty: "Medium" },
    { name: "Palindromic Substrings", url: LC("palindromic-substrings"), difficulty: "Medium" },
    { name: "Decode Ways", url: LC("decode-ways"), difficulty: "Medium" },
    { name: "Coin Change", url: LC("coin-change"), difficulty: "Medium" },
    { name: "Maximum Product Subarray", url: LC("maximum-product-subarray"), difficulty: "Medium" },
    { name: "Word Break", url: LC("word-break"), difficulty: "Medium" },
    { name: "Partition Equal Subset Sum", url: LC("partition-equal-subset-sum"), difficulty: "Medium" },
  ]},
  { id: "intervals", label: "Intervals", x: 5, y: 6, prerequisites: ["heap"], problems: [
    { name: "Meeting Rooms", url: LC("meeting-rooms"), difficulty: "Easy" },
    { name: "Meeting Rooms II", url: LC("meeting-rooms-ii"), difficulty: "Medium" },
    { name: "Insert Interval", url: LC("insert-interval"), difficulty: "Medium" },
    { name: "Merge Intervals", url: LC("merge-intervals"), difficulty: "Medium" },
    { name: "Non-overlapping Intervals", url: LC("non-overlapping-intervals"), difficulty: "Medium" },
    { name: "Min Interval Including Query", url: LC("minimum-interval-to-include-each-query"), difficulty: "Hard" },
  ]},
  { id: "greedy", label: "Greedy", x: 22, y: 6, prerequisites: ["heap"], problems: [
    { name: "Maximum Subarray", url: LC("maximum-subarray"), difficulty: "Medium" },
    { name: "Jump Game", url: LC("jump-game"), difficulty: "Medium" },
    { name: "Jump Game II", url: LC("jump-game-ii"), difficulty: "Medium" },
    { name: "Gas Station", url: LC("gas-station"), difficulty: "Medium" },
    { name: "Hand of Straights", url: LC("hand-of-straights"), difficulty: "Medium" },
    { name: "Merge Triplets to Target", url: LC("merge-triplets-to-form-target-triplet"), difficulty: "Medium" },
    { name: "Partition Labels", url: LC("partition-labels"), difficulty: "Medium" },
    { name: "Valid Parenthesis String", url: LC("valid-parenthesis-string"), difficulty: "Medium" },
  ]},
  { id: "adv-graphs", label: "Advanced Graphs", x: 38, y: 6, prerequisites: ["graphs"], problems: [
    { name: "Reconstruct Itinerary", url: LC("reconstruct-itinerary"), difficulty: "Hard" },
    { name: "Min Cost Connect Points", url: LC("min-cost-to-connect-all-points"), difficulty: "Medium" },
    { name: "Network Delay Time", url: LC("network-delay-time"), difficulty: "Medium" },
    { name: "Swim in Rising Water", url: LC("swim-in-rising-water"), difficulty: "Hard" },
    { name: "Cheapest Flights K Stops", url: LC("cheapest-flights-within-k-stops"), difficulty: "Medium" },
    { name: "Alien Dictionary", url: LC("alien-dictionary"), difficulty: "Hard" },
  ]},
  { id: "dp2", label: "2-D DP", x: 58, y: 6, prerequisites: ["dp1", "graphs"], problems: [
    { name: "Unique Paths", url: LC("unique-paths"), difficulty: "Medium" },
    { name: "Longest Common Subsequence", url: LC("longest-common-subsequence"), difficulty: "Medium" },
    { name: "Best Time Buy Sell Cooldown", url: LC("best-time-to-buy-and-sell-stock-with-cooldown"), difficulty: "Medium" },
    { name: "Coin Change II", url: LC("coin-change-ii"), difficulty: "Medium" },
    { name: "Target Sum", url: LC("target-sum"), difficulty: "Medium" },
    { name: "Interleaving String", url: LC("interleaving-string"), difficulty: "Medium" },
    { name: "Longest Increasing Subseq", url: LC("longest-increasing-subsequence"), difficulty: "Medium" },
    { name: "Edit Distance", url: LC("edit-distance"), difficulty: "Medium" },
    { name: "Distinct Subsequences", url: LC("distinct-subsequences"), difficulty: "Hard" },
    { name: "Burst Balloons", url: LC("burst-balloons"), difficulty: "Hard" },
    { name: "Regular Expression Match", url: LC("regular-expression-matching"), difficulty: "Hard" },
  ]},
  { id: "bit", label: "Bit Manipulation", x: 78, y: 6, prerequisites: ["dp1"], problems: [
    { name: "Single Number", url: LC("single-number"), difficulty: "Easy" },
    { name: "Number of 1 Bits", url: LC("number-of-1-bits"), difficulty: "Easy" },
    { name: "Counting Bits", url: LC("counting-bits"), difficulty: "Easy" },
    { name: "Reverse Bits", url: LC("reverse-bits"), difficulty: "Easy" },
    { name: "Missing Number", url: LC("missing-number"), difficulty: "Easy" },
    { name: "Sum of Two Integers", url: LC("sum-of-two-integers"), difficulty: "Medium" },
    { name: "Reverse Integer", url: LC("reverse-integer"), difficulty: "Medium" },
  ]},
  { id: "math", label: "Math & Geometry", x: 50, y: 7, prerequisites: ["dp2", "bit"], problems: [
    { name: "Happy Number", url: LC("happy-number"), difficulty: "Easy" },
    { name: "Plus One", url: LC("plus-one"), difficulty: "Easy" },
    { name: "Rotate Image", url: LC("rotate-image"), difficulty: "Medium" },
    { name: "Spiral Matrix", url: LC("spiral-matrix"), difficulty: "Medium" },
    { name: "Set Matrix Zeroes", url: LC("set-matrix-zeroes"), difficulty: "Medium" },
    { name: "Pow(x,n)", url: LC("powx-n"), difficulty: "Medium" },
    { name: "Multiply Strings", url: LC("multiply-strings"), difficulty: "Medium" },
    { name: "Detect Squares", url: LC("detect-squares"), difficulty: "Medium" },
  ]},
];

export const EDGES: Edge[] = [];
NODES.forEach(n => n.prerequisites?.forEach(p => EDGES.push({ from: p, to: n.id })));

export const DIFF_COLORS: Record<string, string> = { Easy: "text-green-400", Medium: "text-yellow-400", Hard: "text-red-400" };
